# Generated by Django 5.2.5 on 2025-10-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='slug',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='etiqueta',
            field=models.CharField(blank=True, choices=[('', '—'), ('nuevo', 'Nuevo'), ('oferta', 'Oferta')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_mascota',
            field=models.CharField(blank=True, choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='url_amigable',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='valoracion',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
