# Generated by Django 5.2.6 on 2025-10-25 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_disponibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('rut', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=120, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='M', max_length=1)),
                ('especie', models.CharField(max_length=60)),
                ('raza', models.CharField(blank=True, max_length=120, null=True)),
                ('color', models.CharField(blank=True, max_length=120, null=True)),
                ('caracteristica', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('microchip', models.CharField(blank=True, max_length=60, null=True)),
                ('esterilizado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='agenda.propietario')),
            ],
        ),
    ]
