# Generated by Django 5.2.6 on 2025-11-15 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_cajamovimiento_id_alter_cajasesion_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='direccion_entrega',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='email_cliente',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='venta',
            name='nombre_cliente',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='venta',
            name='notas_cliente',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='venta',
            name='rut_cliente',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='telefono_cliente',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('WEBPAY', 'Webpay (Transbank)')], default='EFECTIVO', max_length=30),
        ),
        migrations.CreateModel(
            name='PagoTransbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('buy_order', models.CharField(max_length=26)),
                ('session_id', models.CharField(max_length=60)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('CREADA', 'Creada'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada'), ('ANULADA', 'Anulada'), ('ERROR', 'Error')], default='CREADA', max_length=20)),
                ('authorization_code', models.CharField(blank=True, default='', max_length=20)),
                ('payment_type', models.CharField(blank=True, default='', max_length=12)),
                ('installments', models.PositiveIntegerField(blank=True, null=True)),
                ('accounting_date', models.CharField(blank=True, default='', max_length=10)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('email_enviado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_transbank', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Pago Webpay',
                'verbose_name_plural': 'Pagos Webpay',
            },
        ),
    ]
