# Generated by Django 5.2.6 on 2025-10-06 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion_min_default',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='servicio',
            name='icono',
            field=models.CharField(blank=True, default='🐾', max_length=8),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('fecha', 'hora', 'profesional'), name='uniq_cita_por_profesional_fecha_hora'),
        ),
    ]
