# Generated by Django 5.2.6 on 2025-11-15 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('otro', 'Otro')], default='perro', max_length=12)),
                ('raza', models.CharField(blank=True, max_length=120)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/mascotas/')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mascota de usuario',
                'verbose_name_plural': 'Mascotas de usuario',
                'ordering': ['nombre'],
            },
        ),
    ]
