# Generated by Django 5.2.6 on 2025-10-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajamovimiento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cajasesion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PAGADA', 'Pagada'), ('ANULADA', 'Anulada'), ('PENDIENTE', 'Pendiente')], default='PAGADA', max_length=30),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=30),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='ventaitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ventaitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterModelTable(
            name='venta',
            table='ventas_venta',
        ),
        migrations.AlterModelTable(
            name='ventaitem',
            table='ventas_ventaitem',
        ),
    ]
